CREATE TABLE FileType (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) not null UNIQUE,
  "mime_type" varchar(255) not null
);

CREATE TABLE File (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp not null,
  "title" varchar(255) not null,
  "hash" varchar(255) not null UNIQUE,
  "path" varchar(2048) not null,
  "type_id" int
);

-- count: 2
CREATE TABLE Account (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp not null default current_timestamp,
  "username" varchar(255) not null,
  "email" varchar(255) not null,
  "password" varchar(255) not null,
  "avatar_id" int default null
);

CREATE TABLE Role (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) not null
);

CREATE TABLE Role_Account (
  "role_id" int not null,
  "account_id" int not null,
  PRIMARY KEY ("role_id", "account_id")
);

-- count: 5
CREATE TABLE Project (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp not null default current_timestamp,
  "title" varchar(255) not null,
  "description" varchar(255),
  "owner_id" int not null
);

-- count: 12
CREATE TABLE ProjectAccessKey (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp not null default current_timestamp,
  "title" varchar(255) not null,
  "value" varchar(255) not null,
  "project_id" int not null
);

-- count: 5
CREATE TABLE DevicePlatform (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) not null
);

-- count: 30
CREATE TABLE ProjectDevice (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp not null default current_timestamp,
  "title" varchar(255) not null,
  "platform_id" int not null
);

-- count: 100
CREATE TABLE ProjectUser (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp not null default current_timestamp,
  "client_key" varchar(255),
  "identify_key" varchar(255),
  "project_id" int not null
);

-- count: 10
CREATE TABLE FunctionTag (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) not null
);

-- count: 300
CREATE TABLE ProjectFunction (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp not null default current_timestamp,
  "title" varchar(255) not null,
  "project_id" int not null
);

CREATE TABLE Function_Tag (
  "tag_id" int not null,
  "function_id" int not null,
  PRIMARY KEY ("tag_id", "function_id")
);

-- count: 70
CREATE TABLE ProjectFeature (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp not null default current_timestamp,
  "title" varchar(255) not null,
  "description" varchar(255),
  "project_id" int not null
);

CREATE TABLE Function_Feature (
  "feature_id" int not null,
  "function_id" int not null,
  PRIMARY KEY ("feature_id", "function_id")
);

-- count: 1000
CREATE TABLE Event (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp not null default current_timestamp,
  "function_id" int not null,
  "user_id" int not null,
  "device_id" int
);

-- count: 1000
CREATE TABLE Error (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp not null default current_timestamp,
  "user_id" int not null,
  "device_id" int not null,
  "message" text not null
);
