CREATE TABLE file_type
(
    "id"        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title"     varchar(255) not null UNIQUE,
    "mime_type" varchar(255) not null
);

CREATE TABLE file
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp     not null,
    "title"      varchar(255)  not null,
    "hash"       varchar(255)  not null UNIQUE,
    "path"       varchar(2048) not null,
    "type_id"    int
);

-- count: 2
CREATE TABLE account
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp    not null default current_timestamp,
    "username"   varchar(255) not null,
    "email"      varchar(255) not null,
    "password"   varchar(255),
    "avatar_id"  int                   default null
);

CREATE TABLE role
(
    "id"    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" varchar(255) not null
);

CREATE TABLE role_account_ref
(
    "role_id"    int not null,
    "account_id" int not null,
    PRIMARY KEY ("role_id", "account_id")
);

-- count: 5
CREATE TABLE project
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"  timestamp    not null default current_timestamp,
    "title"       varchar(255) not null,
    "description" varchar(255),
    "owner_id"    int          not null,
    "deleted"     boolean      not null default false
);

-- count: 12
CREATE TABLE project_access_key
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp    not null default current_timestamp,
    "title"      varchar(255) not null,
    "value"      varchar(255) not null,
    "project_id" int          not null
);

-- count: 5
CREATE TABLE device_platform
(
    "id"    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" varchar(255) not null
);

-- count: 30
CREATE TABLE project_device
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"  timestamp    not null default current_timestamp,
    "title"       varchar(255) not null,
    "platform_id" int          not null
);

-- count: 100
CREATE TABLE project_user
(
    "id"           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"   timestamp not null default current_timestamp,
    "client_key"   varchar(255),
    "identify_key" varchar(255),
    "project_id"   int       not null
);

-- count: 10
CREATE TABLE function_tag
(
    "id"    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" varchar(255) not null
);

-- count: 300
CREATE TABLE project_function
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp    not null default current_timestamp,
    "title"      varchar(255) not null,
    "project_id" int          not null,
    "deleted"    boolean      not null default false
);

CREATE TABLE function_tag_ref
(
    "tag_id"      int not null,
    "function_id" int not null,
    PRIMARY KEY ("tag_id", "function_id")
);

-- count: 70
CREATE TABLE project_feature
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"  timestamp    not null default current_timestamp,
    "title"       varchar(255) not null,
    "description" varchar(255),
    "project_id"  int          not null,
    "deleted"     boolean      not null default false
);

CREATE TABLE function_feature_ref
(
    "feature_id"  int not null,
    "function_id" int not null,
    PRIMARY KEY ("feature_id", "function_id")
);

-- count: 500000
CREATE TABLE event
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"  timestamp not null default current_timestamp,
    "function_id" int       not null,
    "user_id"     int       not null,
    "device_id"   int
);

-- count: 1000
CREATE TABLE error
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"  timestamp not null default current_timestamp,
    "user_id"     int       not null,
    "device_id"   int       not null,
    "function_id" int,
    "message"     text      not null
);
