server:
  port: ${PORT:8080}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}

app:
  token:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}
    audience: ${JWT_AUDIENCE}
    ttl: ${JWT_TTL}
  resources:
    resources-url: ${SERVER_URL}/account/avatar/
  storage:
    store-path: ${STORE_PATH}
    file-name-pattern: "{FILE_HASH}_{TIMESTAMP}.{EXTENSION}"
  oauth:
    github:
      client-id: ${GITHUB_CLIENT_ID}
      client-secret: ${GITHUB_CLIENT_SECRET}
  cors:
    - ${WORKSPACE_URL}
