server:
  port: ${API_PORT:8080}
  servlet:
    contextPath: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}

app:
  token:
    secret: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    issuer: http://localhost/
    audience: http://localhost/
    ttl: 604800000
  resources:
    resources-url: /account/avatar/
  storage:
    store-path: ${STORE_PATH}
    file-name-pattern: "{FILE_HASH}_{TIMESTAMP}.{EXTENSION}"
